#
# Ralink/MediaTek Platform Support
#
snd-soc-ralink-i2s-objs := ralink-i2s.o

obj-$(CONFIG_SND_RALINK_SOC_I2S) += snd-soc-ralink-i2s.o

snd-soc-mt7628-wm8960-objs := mt7628-wm8960.o

obj-$(CONFIG_SND_MT7628_SOC_WM8960) += snd-soc-mt7628-wm8960.o
