#
# Ralink/MediaTek Platform Support
#
snd-soc-ralink-i2s-objs := ralink-i2s.o

obj-$(CONFIG_SND_RALINK_SOC_I2S) += snd-soc-ralink-i2s.o

snd-soc-mt76x8-wm8960-objs := mt76x8-wm8960.o

obj-$(CONFIG_SND_MT76X8_SOC_WM8960) += snd-soc-mt76x8-wm8960.o
