#
# Ralink/MediaTek Platform Support
#

# platform driver
snd-soc-ralink-i2s-objs := ralink-i2s.o
obj-$(CONFIG_SND_SOC_RALINK_I2S) += snd-soc-ralink-i2s.o

# machine driver
snd-soc-mt76x8-wm8960-objs := mt76x8-wm8960.o
obj-$(CONFIG_SND_SOC_MT76X8_WM8960) += snd-soc-mt76x8-wm8960.o
